name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build for Windows
      run: flutter build windows --release

    - name: Create release directory
      run: mkdir -p releases/windows

    - name: Copy Windows build
      run: xcopy "build/windows/x64/runner/Release" "releases/windows" /E /I /Y

    - name: Configure Git
      run: |
        git config --local user.email "amr.hendawy44165@gmail.com"
        git config --local user.name "Hendawy44165"

    - name: Commit and push release files
      run: |
        git add releases/
        git commit -m "Windows release build"
        git push